[package]
name = "rust-2048"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
yew = { version = "0.20", features = ["csr"] }
getrandom = { version = "0.2.9", features = ["js"] }

